"""
Defines the official Senzing Entity Specification keys to validate and guide the extraction logic.
"""

RECORD_TYPE_KEYS = {"RECORD_TYPE"}

NAME_KEYS = {
    "NAME_TYPE", "NAME_FIRST", "NAME_MIDDLE", "NAME_LAST", 
    "NAME_PREFIX", "NAME_SUFFIX", "NAME_ORG", "NAME_FULL"
}

ADDR_KEYS = {
    "ADDR_TYPE", "ADDR_LINE1", "ADDR_LINE2", "ADDR_LINE3", 
    "ADDR_LINE4", "ADDR_LINE5", "ADDR_LINE6", "ADDR_CITY", 
    "ADDR_STATE", "ADDR_POSTAL_CODE", "ADDR_COUNTRY", "ADDR_FULL"
}

CONTACT_KEYS = {
    "PHONE_TYPE", "PHONE_NUMBER", "EMAIL_ADDRESS"
}

CHARACTERISTICS_KEYS = {
    "GENDER", "DATE_OF_BIRTH", "DATE_OF_DEATH", "NATIONALITY", 
    "CITIZENSHIP", "PLACE_OF_BIRTH", "REGISTRATION_DATE", "REGISTRATION_COUNTRY"
}

IDENTIFIER_KEYS = {
    "PASSPORT_NUMBER", "PASSPORT_COUNTRY",
    "DRIVERS_LICENSE_NUMBER", "DRIVERS_LICENSE_STATE",
    "SSN_NUMBER", 
    "NATIONAL_ID_NUMBER", "NATIONAL_ID_TYPE", "NATIONAL_ID_COUNTRY",
    "TAX_ID_NUMBER", "TAX_ID_TYPE", "TAX_ID_COUNTRY",
    "OTHER_ID_NUMBER", "OTHER_ID_TYPE", "OTHER_ID_COUNTRY",
    "ACCOUNT_NUMBER", "ACCOUNT_DOMAIN", 
    "DUNS_NUMBER", "NPI_NUMBER", "LEI_NUMBER"
}

SOCIAL_KEYS = {
    "WEBSITE_ADDRESS", "LINKEDIN", "FACEBOOK", "TWITTER", "INSTAGRAM", "SKYPE",
    "WHATSAPP", "SIGNAL", "TELEGRAM", "TANGO", "VIBER", "WECHAT"
}

STANDARD_FEATURE_KEYS = set().union(
    RECORD_TYPE_KEYS, NAME_KEYS, ADDR_KEYS, CONTACT_KEYS, 
    CHARACTERISTICS_KEYS, IDENTIFIER_KEYS, SOCIAL_KEYS
)
